
openapi: 3.0.0
info:
  title: Ponies
  version: '1.0'
  contact:
    name: Zomzog
  description: Pony management API
servers:
  - url: 'http://localhost:3000'
paths:
  '/ponies/{ponyId}':
    parameters:
      - schema:
          type: integer
        name: ponyId
        in: path
        required: true
    get:
      summary: Get Pony Info by Pony ID
      responses:
        '200':
          description: Pony Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pony'
              examples: {}
        '404':
          description: Pony Not Found
      operationId: get-one
      description: Retrieve the information of the Pony with the matching Pony ID.
      tags:
        - ponies
    put:
      summary: Update Pony Information
      operationId: update-Ponys-PonyId
      responses:
        '200':
          description: Pony Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pony'
              examples: {}
        '404':
          description: Pony Not Found
        '409':
          description: Email Already Taken
      description: Update the infromation of an existing Pony.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pony'
            examples: {}
        description: Update Pony properties.
      tags:
        - ponies
  /ponies:
    post:
      summary: Create New Pony
      operationId: post-Pony
      responses:
        '200':
          description: Pony Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pony'
              examples: {}
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pony'
            examples: {}
        description: Post the necessary fields for the API to create a new Pony.
      description: Create a new Pony.
      tags:
        - ponies
    parameters: []
components:
  schemas:
    Pony:
      title: Pony
      type: object
      description: ''
      x-examples: {}
      properties:
        id:
          type: integer
          description: Unique identifier for the given Pony.
        name:
          type: string
        type:
          $ref: '#/components/schemas/PonyType'
        friends:
          type: array
          uniqueItems: true
          items:
            $ref: ''
      required:
        - id
        - name
        - type
    PonyType:
      type: string
      title: PonyType
      enum:
        - Earth
        - Unicorns
        - Pegasi
tags:
  - name: ponies